const alphabet = {
  "default": {
    "triangleX": 0,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    "snakeY": 0,
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "A": {
    "triangleX": 52,
    "triangleY": 60,
    "rect1X": 12,
    "rect1Y": 148,
    "rect2X": 90,
    "rect2Y": 148,
    "snakeX": 32,
    "snakeY": 106,
    "snakeLength": 3,
    "snakeRot": 0,
    "rect1Rot": 75.6,
    "rect2Rot": 72,
    "triangleRot": 86.3999999999
  },
  "B": {
    "triangleX": 42,
    "triangleY": 50,
    "rect1X": 20,
    "rect1Y": 150,
    "rect2X": 58,
    "rect2Y": 166,
    "snakeX": 35,
    "snakeY": 120,
    "snakeLength": 3,
    "snakeRot": 120,
    "rect1Rot": 147.6,
    "rect2Rot": 180,
    "triangleRot": 0
  },
  "C": {
    "triangleX": 40,
    "triangleY": 95,
    "rect1X": 66.46,
    "rect1Y": 33,
    "rect2X": 73.42,
    "rect2Y": 161,
    "snakeX": 0,
    "snakeY": 135,
    "snakeLength": 5,
    "snakeRot": 277.2,
    "rect1Rot": 51.104,
    "rect2Rot": 124.848,
    "triangleRot": 237.708
  },
  "D": {
    "triangleX": 66,
    "triangleY": 95,
    "rect1X": 36,
    "rect1Y": 33,
    "rect2X": 36,
    "rect2Y": 161,
    "snakeX": -15,
    "snakeY": 40,
    "snakeLength": 6,
    "snakeRot": 234,
    "rect1Rot": 190.8,
    "rect2Rot": 104.4,
    "triangleRot": 0
  },
  "E": {
    "triangleX": 36,
    "triangleY": 100,
    "rect1X": 50,
    "rect1Y": 32,
    "rect2X": 50,
    "rect2Y": 168,
    "snakeX": -15,
    "snakeY": 40,
    "snakeLength": 6,
    "snakeRot": 234,
    "rect1Rot": 86.39999999,
    "rect2Rot": 259.2,
    "triangleRot": 0
  },
  "F": {
    "triangleX": 36,
    "triangleY": 75,
    "rect1X": 55,
    "rect1Y": 30,
    "rect2X": 25,
    "rect2Y": 150,
    "snakeX": 75,
    "snakeY": 60,
    "snakeLength": 3,
    "snakeRot": 172.7999999,
    "rect1Rot": 86.39999999,
    "rect2Rot": 172.7999999,
    "triangleRot": 0
  },
  "G": {
    "triangleX": 78,
    "triangleY": 154,
    "rect1X": 82,
    "rect1Y": 56,
    "rect2X": 28,
    "rect2Y": 54,
    "snakeX": 59.7,
    "snakeY": 165,
    "snakeLength": 4,
    "snakeRot": 205.2,
    "rect1Rot": 266.4,
    "rect2Rot": 252,
    "triangleRot": 28.8
  },
  "H": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    "snakeY": 0,
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "I": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "J": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "K": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "L": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "M": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "N": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "O": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "P": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "Q": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "R": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "S": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "T": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "U": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "V": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "W": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "X": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "Y": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "Z": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "0": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "1": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "2": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "3": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "4": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "5": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "6": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "7": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "8": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  },
  "9": {
    "triangleX": 40,
    "triangleY": 0,
    "rect1X": 0,
    "rect1Y": 0,
    "rect2X": 0,
    "rect2Y": 0,
    "snakeX": 0,
    
    "snakeLength": 5,
    "snakeRot": 0,
    "rect1Rot": 0,
    "rect2Rot": 0,
    "triangleRot": 0
  }

}